validation-hint & form updates
gtmhub/figmaTokens pull request #88
Opened 2023-03-10 12:53 UTC by Ddungyov

2023-03-10 15:15 UTC, StefanIvanov requested changes

2023-03-10 15:15 UTC, StefanIvanov commented on data/tokens.json
> -              "color": "{Primary.gtmds_color_primary-focus}",
All above this line are changes that shouldn't be there ...

2023-03-14 15:18 UTC, StefanIvanov commented on data/tokens.json
> -        "gtmds_hint_color": {
Shows me that you removed this, why?

2023-03-14 15:18 UTC, StefanIvanov commented on data/tokens.json
> -        "gtmds_hint_color": {
This one also...
Maybe we need a quick huddle as I cannot follow what you wanted to achieve :)

2023-03-20 11:38 UTC, Ddungyov commented
> @Ddungyov were you able to prepare the final commit we talked about last week?

Yes, I have committed a new update based on the "next" branch.

2023-03-20 12:09 UTC, StefanIvanov commented
> > @Ddungyov were you able to prepare the final commit we talked about last week?
> 
> Yes, I have committed a new update based on the "next" branch.

But I see no commits here

2023-03-20 12:15 UTC, Ddungyov commented
> 
it should be this one
[52a809e](https://github.com/gtmhub/figmaTokens/pull/88/commits/52a809e913cdc71e5b1ca44de8f0e29afbcabce4)

2023-03-20 12:21 UTC, StefanIvanov approved these changes

2023-03-20 12:21 UTC, StefanIvanov commented on data/tokens.json
>          "gtmds_hint-message_color": {
```suggestion
        "gtmds_hint_color": {
```

2023-03-20 12:22 UTC, merged