fixing the date picker
gtmhub/figmaTokens pull request #90
Opened 2023-03-15 13:10 UTC by Ddungyov

2023-03-15 15:00 UTC, Ddungyov commented on data/tokens.json
> +      "value": "{gtmds_color_white}01",
оpacity 😆

2023-03-20 09:53 UTC, StefanIvanov commented on data/tokens.json
> +      "value": "{gtmds_color_white}01",
rgba({gtmds_color_white}, 0.1)

2023-03-20 11:43 UTC, Ddungyov commented on data/tokens.json
> +      "value": "{gtmds_color_white}01",
fixed :). Didn't knew that, love it.

2023-03-20 12:08 UTC, StefanIvanov requested changes

2023-03-20 12:08 UTC, StefanIvanov commented on data/tokens.json
> +      "value": "({gtmds_color_white}, 0.1)",
```suggestion
      "value": "rgba({gtmds_color_white}, 0.1)", 
```

2023-03-20 12:23 UTC, StefanIvanov approved these changes

2023-03-20 12:23 UTC, merged