Onboarding color added
gtmhub/figmaTokens pull request #98
Opened 2023-04-10 13:51 UTC by alicequantive

2023-04-11 06:50 UTC, StefanIvanov requested changes

2023-04-11 06:50 UTC, StefanIvanov commented on data/tokens.json
> +    "onboarding": {
```suggestion
    "Onboarding": {
```

2023-04-11 06:50 UTC, StefanIvanov commented on data/tokens.json
> +        "value": "{gtmds_color_gray-1}",
```suggestion
        "value": "{gtmds_color_white}",
```

2023-04-11 06:50 UTC, StefanIvanov commented on data/tokens.json
> +        "value": "{gtmds_color_gray-1}",
lets define it like this because our goal is for the text to be white and in case we change at some point the grays palette it might not be the case anymore that gray-1 is white anymore

2023-04-11 06:50 UTC, StefanIvanov commented on data/tokens.json
> +      }
I can't figure out where and how we use this in Figma so I left a comment there and let's use it to help me understand

2023-04-12 09:41 UTC, StefanIvanov approved these changes

2023-04-20 10:43 UTC, Ddungyov commented on data/tokens.json
> +      "gtmds_popover-footer-stepper_size-width": {
What's this token for? @alicequantive

2023-04-26 07:36 UTC, Ddungyov approved these changes

2023-04-26 09:09 UTC, merged